import Footer from 'components/Footer'
import Header from 'components/Header'
import '@styles/globals.css'
import '@styles/layout.css'
import Head from 'next/head'
import Navbar from 'components/Navbar'
import { SessionProvider } from 'next-auth/react'

export default function App({ Component, pageProps }) {
  if(Component.getLayout) {
    return Component.getLayout(<Component {...pageProps} />)
  }

  const title = "HI I am nooneneoneoneniae";

  return <>
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by Me" />
    </Head>
    <Header/>
    <SessionProvider session={pageProps.session}>
      <Navbar/>
      <Component {...pageProps} />
    </SessionProvider>
    <Footer/>
  </>
}
