import { useSession } from "next-auth/react";
import Head from "next/head";

export default function Home() {
  const { data: session, status } = useSession();
  console.log(session, status);
  return (
    <>
      <Head>
        <meta name="description" content="Generated by Me" />
      </Head>
      <div>{status === "authenticated" ? "Gaurav Kumar" : ""} Next JS pre rendering</div>
    </>
  )
}
